import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Home from './home';
import Layout from '@/components/features/Layout';
import HomeComponent from '@/components/pages/Home';

const inter = Inter({ subsets: ['latin'] });

export default function Main() {
  return (
    <>
      <Head>
        <title>Eco Kamen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <Layout>
          <HomeComponent />
        </Layout>
      
    </>
  );
}
